import Head from 'next/head';

export default function Home() {
  return (
    <>
      <Head>
        <title>Next Trivia</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className='bg-red-200'>
        <h1>Hola</h1>
      </main>
    </>
  );
}
